spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: timewise-event
          uri: http://localhost:58340/event/
          predicates:
            - Path=/event/**
          filters:
            - AuthenticationFilter
        - id: timewise-security
          uri: http://localhost:53945/auth/
          predicates:
            - Path=/auth/**